"""Speech-to-text, Gemini reasoning, and text-to-speech helpers."""
import io
import os
import tempfile

from flask import current_app

from app.services.gemini_service import ask_farmer_voice


LANGUAGE_CODES = {"en": "en-IN", "hi": "hi-IN", "kn": "kn-IN"}


def transcribe_audio(audio_stream, filename, language="en"):
    """Transcribe a WAV/AIFF/FLAC upload with SpeechRecognition's free recognizer."""
    try:
        import speech_recognition as sr
    except ImportError as error:
        raise RuntimeError("SpeechRecognition is not installed.") from error

    suffix = os.path.splitext(filename or "audio.wav")[1].lower() or ".wav"
    if suffix not in {".wav", ".aiff", ".aif", ".flac"}:
        raise RuntimeError("Upload a WAV, AIFF, or FLAC audio file for voice input.")

    recognizer = sr.Recognizer()
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as temporary:
            audio_stream.save(temporary.name)
            temporary_path = temporary.name
        with sr.AudioFile(temporary_path) as source:
            audio = recognizer.record(source)
        return recognizer.recognize_google(audio, language=LANGUAGE_CODES.get(language, "en-IN"))
    except sr.UnknownValueError as error:
        raise RuntimeError("I could not understand the audio. Please speak again.") from error
    except sr.RequestError as error:
        raise RuntimeError("Speech recognition is unavailable. Check the network and try again.") from error
    finally:
        if temporary_path:
            try:
                os.remove(temporary_path)
            except OSError:
                pass


def synthesize_speech(text, language="en"):
    """Return MP3 audio bytes generated by gTTS."""
    try:
        from gtts import gTTS
    except ImportError as error:
        raise RuntimeError("gTTS is not installed.") from error

    output = io.BytesIO()
    gTTS(text=text, lang={"en": "en", "hi": "hi", "kn": "kn"}.get(language, "en"), slow=False).write_to_fp(output)
    output.seek(0)
    return output


def process_voice_request(question, audio_file, language="en", context=""):
    if audio_file is not None:
        question = transcribe_audio(audio_file, audio_file.filename, language)
    if not question or not question.strip():
        raise ValueError("Send text or an audio recording.")
    reply = ask_farmer_voice(question.strip(), language, context)
    return question.strip(), reply, synthesize_speech(reply, language)
